single pool wallet for every job created
madrugada-labs/candidate-staking pull request #16
Opened 2022-07-19 17:13 UTC by dhruvja

2022-07-19 17:15 UTC, dhruvja commented
there are some changes which are left, will add soon

2022-07-30 21:02 UTC, blasrodri commented on programs/job/src/lib.rs
> +        // constraint=wallet_to_withdraw_from.mint == token_mint.key()
```suggestion
```

2022-07-30 21:03 UTC, blasrodri commented on programs/job/src/lib.rs
> +            // This pattern is common in Rust.
```suggestion
```

2022-07-30 21:03 UTC, blasrodri commented on programs/job/src/lib.rs
> +        // let candidate_parameters = &mut ctx.accounts.candidate_account;
```suggestion
```

2022-07-30 21:03 UTC, blasrodri commented on programs/candidate_staking/src/lib.rs
> +    pub base_account: Box<Account<'info, CandidateParameter>>,
why box? what happens if we don't?

2022-07-30 21:03 UTC, blasrodri commented on programs/candidate_staking/Cargo.toml
> +anchor-lang = {version = "0.24.2", features = ["init-if-needed"]}
can you please elaborate on why we need this?

2022-07-30 21:04 UTC, blasrodri commented
Check https://github.com/coral-xyz/anchor/issues/1191#issuecomment-1005188435 for `init-in-needed`. We should try to avoid

2022-07-30 21:05 UTC, blasrodri requested changes
Can we try to do this without init-if-needed?

2022-07-31 03:03 UTC, dhruvja commented
> Can we try to do this without init-if-needed?

We can but since it's a token account which is getting initialized, I don't see any problem in using init-if-needed.

2022-07-31 08:08 UTC, blasrodri commented
> > Can we try to do this without init-if-needed?
> 
> We can but since it's a token account which is getting initialized, I don't see any problem in using init-if-needed.

Can you explain me why we need this feature?

2022-08-18 19:35 UTC, closed without merging